### PR TITLE
feat: add extraLabels

### PR DESCRIPTION
**Pull request by lenglet-k**
On this PR i've added `extraLabels` field, the goal is to custom labels in deployement and pod object. 

Test:

```shell
helm plugin ls | grep unittest || helm plugin install https://github.com/helm-unittest/helm-unittest.git
unittest	0.3.6  	Unit test for helm chart in YAML with ease to keep your chart functional and robust.
helm unittest -f 'test/lint/*.yaml' .

### Chart [ apicurio-registry ] .

2023/11/29 09:54:54 warning: cannot overwrite table with non table for apicurio-registry.registry.nodeSelector (map[])
2023/11/29 09:54:54 warning: cannot overwrite table with non table for apicurio-registry.registry.ingress (map[annotations:map[] enabled:false host:apicurio.local ingressClassName: labels:map[] path:/ tls:false])
2023/11/29 09:54:54 warning: cannot overwrite table with non table for apicurio-registry.registry.extraLabels (map[])
 PASS  lint registry values	test/lint/registry.yaml
2023/11/29 09:54:54 warning: cannot overwrite table with non table for apicurio-registry.sync.extraLabels (map[])
2023/11/29 09:54:54 warning: cannot overwrite table with non table for apicurio-registry.sync.nodeSelector (map[])
 PASS  lint sync values	test/lint/sync.yaml

Charts:      1 passed, 1 total
Test Suites: 2 passed, 2 total
Tests:       12 passed, 12 total
Snapshot:    0 passed, 0 total
Time:        13.849969ms

helm unittest -f 'test/unit/*.yaml' .

### Chart [ apicurio-registry ] .

 PASS  test deployment-registry.yaml template	test/unit/deployment_registry.yaml
 PASS  test deployment-sync.yaml template	test/unit/deployment_sync.yaml
 PASS  test ingress	test/unit/ingress.yaml
 PASS  test sa	test/unit/sa.yaml

Charts:      1 passed, 1 total
Test Suites: 4 passed, 4 total
Tests:       26 passed, 26 total
Snapshot:    0 passed, 0 total
Time:        52.558546ms

```

### CODE REVIEW

**Review by eshepelyuk — CHANGES_REQUESTED** [review]
Plz remove `(extraLabels)` from commit message and fix typos in it. otherwise LGTM, ready to merge.

**Comment by lenglet-k** [comment]
I have remove (extraLabels) from commit message. It's good for you ?

**Comment by eshepelyuk** [comment]
> I have remove (extraLabels) from commit message. It's good for you ?

thnx, but there is still a typo in commit message, plz fix it.

**Comment by lenglet-k** [comment]
Ok, and is it good?

**Pull request merged**
